export interface SoftaDocument {
  id: string
  title: string
  summary: string
  authorship: string
  filename: string
  type: 'pdf' | 'image'
  category: string
}

export const documents: SoftaDocument[] = [
  // Writings, Speeches & Correspondence (5)
  // Ordered: Newspaper profile first, then chronological, with Deming correspondence paired together
  {
    id: '26a',
    title: 'Judith Orloff in the Daily Camera - Radical Love Foundation Press Coverage (2013)',
    summary: 'A three-page scan of newspaper coverage from the Boulder Daily Camera, dated Wednesday, January 9, 2013. Includes a \'To Do List\' section naming Judith Orloff as the \'Pick of the Day\' for speaking at Red Door Studios, and a two-page \'Up Close\' feature profile by Aimee Heckel titled \'The deeper side of Valentine\'s Day.\' The profile describes Judith Orloff as a Boulder woman who runs the Radical Love Foundation nonprofit, teaching people how to be authentic in relationships using simple, practical techniques. Orloff describes her personal story of childhood Cinderella fairy tale confusion, her mission of teaching acceptance of \'what is\' without interpretations or manipulation, and her approach of dissolving reactive patterned behaviors. The article announces a free public class called \'What is Love? Being in an Authentic Relationship\' on Valentine\'s eve at Red Door Studios, 4439 N. Broadway Unit A, Boulder. Photo credit to Jessica Cuneo for the Camera.',
    authorship: 'Article by Aimee Heckel, Camera Staff Writer, published in the Boulder Daily Camera. Photos by Jessica Cuneo. The subject is Judith Orloff, founder of the Radical Love Foundation.',
    filename: '26a.pdf',
    type: 'pdf',
    category: 'Writings, Speeches & Correspondence',
  },
  {
    id: '21',
    title: 'Secrets - Presentation Visual Notes (May 1984)',
    summary: 'A set of 11 hand-drawn visual notes from a presentation called "Secrets" by Judith, dated May 1984. The illustrations use a visual facilitation style to capture key concepts including: presence vs. content, Buckminster Fuller\'s last lecture, choice and reaction, addictions as unexperienced experiences, duplication, integrity, judgement, getting gotten (being experienced), communication breakdowns (words 7%, voice 38%, body language 55%), the process of education referencing Prigogine, forgiveness (referencing Rev. Terry Cole-Whittaker), and presentation techniques like creating anticipation and using timers. References include Richard Bach\'s "Illusions" and Werner Erhard.',
    authorship: 'Judith Orloff (credited as \'Judith May 84\' on the cover page)',
    filename: '21.pdf',
    type: 'pdf',
    category: 'Writings, Speeches & Correspondence',
  },
  {
    id: '13c',
    title: 'Correspondence with W. Edwards Deming (1992)',
    summary: 'Correspondence between Judith Orloff-Falk and W. Edwards Deming in early 1992. Includes Judith\'s first letter (January 23, 1992) on Educational Discoveries letterhead introducing herself after attending Deming\'s seminar in San Jose, describing her consulting work with Wilcox Memorial Hospital in Kauai, Hawaii (with partner John Dowd) on driving out fear and building constancy of purpose, and enclosing a copy of "Choices for Success." Then Deming\'s personal reply (February 14, 1992) praising her book as "great," expressing his desire to spend time with her, and inviting her criticism and extension of his 4-day seminar content and his forthcoming book "The New Economics." Finally, Judith\'s follow-up letter (February 27, 1992) responding to Deming\'s reply, discussing Japanese vs. American management consciousness, and reporting on their work transforming the culture at Wilcox Memorial Hospital from competition and blame to personal responsibility.',
    authorship: 'Judith Orloff-Falk, Vice President, Educational Discoveries (2511 55th Street, Boulder, CO 80301), and W. Edwards Deming, Ph.D., Consultant in Statistical Studies (4924 Butterworth Place, Washington 20016). Partner Peg Doubleday is also mentioned in Judith\'s letters.',
    filename: '13c.pdf',
    type: 'pdf',
    category: 'Writings, Speeches & Correspondence',
  },
  {
    id: '21a',
    title: 'Emotional Intelligence Project - Interview with Judith Orloff',
    summary: 'A 15-page transcript of a filmed interview with Judith Orloff for an Emotional Intelligence Project. Orloff discusses her preferred term "emotional literacy" over "emotional intelligence," defines it as the ability to be aware of internal experience and respond from that awareness. She addresses gender and cultural differences in emotional expression, how organizations like American Express, Bank of America, Fleet Bank, Midas International, Ford, and GM have adopted EI, and describes her company\'s approach of embedding EI into management training at three levels (beginning, functional, and business managers) rather than selling it as a standalone product. She discusses creating cognitive dissonance to drive real change, the role of franchise organizations in paradigm shifts, and implementation through web-based follow-up modules. She also covers resistance from HR professionals, the connection between emotional intelligence and workplace safety, and her belief that EI is both learned and remembered.',
    authorship: 'Judith Orloff (interviewee). Interviewer is unnamed. Produced as part of an Emotional Intelligence Project (appears to be a video/film production with offstage direction).',
    filename: '21a.pdf',
    type: 'pdf',
    category: 'Writings, Speeches & Correspondence',
  },
  {
    id: '13b',
    title: 'Burlington College Convocation - Judith Orloff\'s Schedule, Speech, and Research Notes (2015)',
    summary: 'Materials from Judith\'s appearance at the Burlington College Convocation on September 9, 2015. Includes her day schedule (executive team meeting, media interviews with VPR and WCAX, trustee meeting, reception), bullet-point speech notes reflecting on co-founding Burlington College in 1972 with Stuart LaCasce and the social movements that shaped their generation (environmentalism, feminism, LGBT rights, civil rights), and background research notes on John Dewey\'s educational philosophy and Debra Meyerson\'s concept of \'tempered radicalism\' as a model for incremental change from within institutions.',
    authorship: 'Speech notes written by Judith Orloff. Schedule prepared by staff (footer: \'LB Corres CM\'). Research notes likely compiled by Judith or an assistant as preparation material.',
    filename: '13b.pdf',
    type: 'pdf',
    category: 'Writings, Speeches & Correspondence',
  },

  // Transformation Programs (11)
  // Ordered: Master manuals, student workbook, then sessions 1-3 with variants, then supplementary exercise
  {
    id: '11a',
    title: 'Extended Teaching Program (ETP) Instructor\'s Manual - DRAFT (Sessions 1-8)',
    summary: 'Draft instructor\'s manual for the Extended Teaching Program (ETP), an 8-session personal responsibility training curriculum created by Quantum Educational Discoveries, Inc. (copyright 1991, revised 04/23/91). Each session spans a multi-day weekend format and covers: owning personal history, living from personal responsibility, integrating the primary family (including a "Mom and Dad Game" and projection exercises), vision and power (with a vision quest and purpose meditation), creating adult relationships (with "schiz-skits" demonstrations), sex/bodies/physical integration (as a retreat with body autobiographies and tantric sexuality discussion), personal integrity (with a "Truth or Consequences" questionnaire), and mastering the process of change. The manual includes detailed instructor notes on facilitation techniques, group exercises, partner work, family day logistics, reading assignments (Richard Bach\'s "Illusions," Jane Roberts\' Seth books, Stephen King\'s "The Talisman," Bernie Siegel, Buckminster Fuller), and curated music selections to close each session. References to Judith Orloff appear in Session 8 notes.',
    authorship: 'Quantum Educational Discoveries, Inc. (QED). No individual author is named on the document, but the final session notes reference Judith (likely Judith Orloff) as someone participants send assignments to, and include personal anecdotes about Judith. The program appears to be an extension of the Choices Weekend created by QED.',
    filename: '11a.pdf',
    type: 'pdf',
    category: 'Transformation Programs',
  },
  {
    id: '4a',
    title: 'Transformation - Student Workbook and Participant Handout Collection',
    summary: 'A student workbook for the Transformation program by Educational Discoveries, containing scheduling pages for three sessions (Our Relationship with Our Selves, Our Relationships with Others, Our Relationship with the Earth), a program evaluation form, a multi-page Reflective Learning Journal with prompts about theories, emotions, paradox, group behaviors, and practical applications, participant handouts on interpretation and projection, an excerpt on "The Human Aura" from Mary Anderson\'s "Color Healing" describing seven auric bodies and levels of consciousness, and a condensed article on the Theory of Dissipative Structures from Marilyn Ferguson\'s "The Aquarian Conspiracy" covering Ilya Prigogine\'s Nobel Prize-winning theory of transformation through perturbation.',
    authorship: 'Educational Discoveries, 5495 Arapahoe Road, Suite 205, Boulder, CO 80303. The program evaluation form is branded "Educational Discoveries / Transformation." The Human Aura section is attributed to Mary Anderson (from "Color Healing"). The Dissipative Structures piece is condensed from Marilyn Ferguson\'s "The Aquarian Conspiracy." Handwritten notes on the Dissipative Structures pages appear to say "reverse July paperly parts" and "Handout These note to read in morning."',
    filename: '4a.pdf',
    type: 'pdf',
    category: 'Transformation Programs',
  },
  {
    id: '4b',
    title: 'ETP II Transformation - Session 1 Instructor\'s Manual',
    summary: 'The complete instructor\'s manual for ETP II Transformation Session 1, structured as a four-day intensive covering "Our Relationship with Our Selves." The manual provides detailed teaching notes for Judith Orloff and co-instructors, covering topics including balancing masculine/feminine nature, chakra system (all seven chakras with colors and functions), dissipative structures and perturbation as mechanisms for change, interpretation and projection, spirit guides, aura exercises at multiple levels, the role of stress in transformation, karma and unconditional love, sacred sexuality, and the concept of "soul homeopathy." References numerous texts including Piers Anthony\'s "Incarnations of Immortality," Robert Johnson\'s "We," "Choices for Success," and "The Wicked Stepmother" fairy tale. Includes exercises, meditations, and between-session assignments. Dated April 18-22, 1991.',
    authorship: 'The document exists in two versions within this PDF. The first version (pages 1-20) is a more detailed instructor\'s manual with bullet-point formatting, attributed to the ETP II Transformation program. The second version (pages 21-37) is a condensed set of teaching notes covering the same Session 1 content. Both are written for/by Judith Orloff as lead instructor, with mentions of participants including Peg, Jack, Cate, Karen, Astrid, Susan, Jonathan, Darrell, Marshall, Nancy, Mary, Brian, and others. The Monroe Institute is referenced for audio resources.',
    filename: '4b.pdf',
    type: 'pdf',
    category: 'Transformation Programs',
  },
  {
    id: '4h',
    title: '"Because There\'s So Much To Learn And So Little Time" - ETP II Session Letter',
    summary: 'A one-page letter dated June 10, 1991, from Judith Orloff and Peg to ETP II participants, announcing that the order of the remaining two sessions has been swapped due to Vermont\'s mosquito season. The June session will now cover relationships and the September session will cover the earth. The letter includes assignments: create a relationship vision and list needed behaviors, read Robert Johnson\'s "We" (and optionally "He" and "She"), and notes that "Natural Acts" is out of print. Participants are told to meet at Patti\'s on Thursday, June 27 at 5:30 pm.',
    authorship: 'Signed by Judith (Orloff) and Peg, on QED (Quantum Educational Discoveries, Inc.) letterhead, 28 Commerce St., P.O. Box 918, Williston, VT 05495. Phone (802) 864-6186, Fax (802) 864-8336.',
    filename: '4h.pdf',
    type: 'pdf',
    category: 'Transformation Programs',
  },
  {
    id: '4k',
    title: 'ETP II Session Two - Program Outline',
    summary: 'A one-page schedule outline for ETP II Transformation Session 2, held June 27-30, 1991. The four-day program covers Thursday evening sharing and connecting around spiritual desires in relationships, Friday sexual healing exercises focused on regaining innocence, Saturday reading and silence, and Sunday relationship work including calling in desired relationships, with assignments given at the close.',
    authorship: 'No author credited on the document. Produced as part of the ETP II Transformation program run by Judith Orloff and Peg Dylan through QED (Quantum Educational Discoveries, Inc.).',
    filename: '4k.pdf',
    type: 'pdf',
    category: 'Transformation Programs',
  },
  {
    id: '4i',
    title: 'ETP II Transformation - Session 2 Instructor\'s Manual (Version A)',
    summary: 'Instructor\'s manual for ETP II Transformation Session 2 focusing on "Our Relationships with Others," structured as a four-day weekend intensive. The first evening opens with connected breathing exercises and covers spiritual essence in relationship, a two-day healing on sexuality, and the concept that change only happens in perturbation and paradox. Day two covers truth-telling in relationships, karma (unconditional love erases karma), sexual healing meditation (to Bolero), parental models of sexuality, and a relationship healing exercise where participants re-create all sexual relationships year by year. Saturday covers leaving relationships (from Emmanuel\'s Book II), integrity, blame, the three-dimensional reality of good/bad, and "The Last Interlude" from Peter Straub\'s Houses Without Doors. Sunday covers spiritual relationships as ordinary, generalized principles of relationship, declarations, "Bar Talk" reading, and closing assignments including reading choices (The Nine Faces of Christ, The Profit by Kahlil Gibran, Firmament of Time by Loren Eiseley, or Memories, Dreams, Reflections by C.G. Jung).',
    authorship: 'Written for the ETP II Transformation program. No specific author credited on the document, but it is clearly an instructor\'s guide for Judith Orloff\'s program based on the content and context within the broader ETP II collection.',
    filename: '4i.pdf',
    type: 'pdf',
    category: 'Transformation Programs',
  },
  {
    id: '4j',
    title: 'Transformation - Session 2 Instructor\'s Manual (Version B)',
    summary: 'An alternative version of the Session 2 instructor\'s manual for the Transformation program, covering the same "Our Relationships with Others" weekend but with slightly different formatting, additional details, and real-time teaching notes from an actual session. Includes references to specific participants (Jack, Karen, Judith, Cate, Jonathan, Darrell, Marshall, Avram, Susan, Peg, Mildred, Mary, Brian) and their relationship dynamics worked through during the session. Contains the same core content as Version A: connected breathing, sexuality healing, karma, projection, relationship principles, and readings from Emmanuel\'s Book II and Peter Straub. Features an Avatar trainer visit during the weekend. Notable for capturing the live, raw quality of the teaching with jokes, real participant interactions, and spontaneous exercises.',
    authorship: 'Written for the Transformation program. The document header reads "Transformation - Instructor\'s Manual - Session 2." References to Judith (Orloff) throughout as instructor, along with mentions of the Ramtha story and specific participant interactions that indicate these are notes from an actual delivered session.',
    filename: '4j.pdf',
    type: 'pdf',
    category: 'Transformation Programs',
  },
  {
    id: '4l',
    title: 'ETP II Transformation - Session 2 Instructor\'s Manual',
    summary: 'Detailed instructor\'s manual for ETP II Transformation Session 2, June 27-30, 1991. Covers teachings on spiritual essence in relationships, sexual healing meditations, projection and how to take projections back, unconditional love erasing karma, personal responsibility, integrity in relationships, and the concept of the \'inverted power group.\' Includes specific facilitation notes for participant interactions with people named Susan, Jack, Gracie, Cate, George, Avram, Kris, and others. References the film \'Thelma and Louise\' as a Saturday activity.',
    authorship: 'No author explicitly credited. Written as an instructor guide for the ETP II Transformation program led by Judith Orloff and Peg Dylan through QED (Quantum Educational Discoveries, Inc.). References \'Judith\' and \'Jack\' as active facilitators/participants.',
    filename: '4l.pdf',
    type: 'pdf',
    category: 'Transformation Programs',
  },
  {
    id: '5b',
    title: 'ETP II Transformation - Session 3 Complete Packet',
    summary: 'A comprehensive 36-page packet for ETP II Transformation Session 3, held September 27-30, 1991, at a river location. Contains the instructor\'s outline covering teachings on projection, self-worth, vision, masculine/feminine energy balancing, the elements (Earth, Air, Fire, Water) integrated into meditations and exercises, and a firewalk. Includes detailed instructor teaching notes spanning three days, a QED cover letter dated October 21, 1991 signed by Judith and Peg, the POP Jokebook Part 3 with humor from participants (Susan F., Patty, George, Lynn, Marlene, Julia, Avram, Jonathan, Michael, Darrell, Sybil), and auxiliary handouts: \'How To Handle a Projection\' (5-step guide), \'Touch the Earth\' meditation compiled by T.C. McLuhan featuring Brave Buffalo\'s account of sacred stones, \'Talking Stones\' meditation technique, \'The Healing Powers of Trees\' reference guide, Transformation Key Teachings compilation (multiple pages of aphorisms across all sessions, dated 10/25/92), a \'Who Should Say What to Whom\' business communication exercise (with handwritten notes referencing \'Hawaii MB2\' and keywords like synergy, teamwork, intimacy, congruence), and a Namaste prayer card.',
    authorship: 'Judith Orloff and Peg Dylan, as indicated by their signatures on the QED cover letter. Produced by Quantum Educational Discoveries, Inc. (QED), 28 Commerce St., P.O. Box 918, Williston, VT 05495. Key Teachings pages dated 10/25/92 with initials \'ss.\' Touch the Earth excerpt compiled by T.C. McLuhan. Talking Stones and Healing Powers of Trees handouts are uncredited supplementary materials branded with the Transformation footer.',
    filename: '5b.pdf',
    type: 'pdf',
    category: 'Transformation Programs',
  },
  {
    id: '4g',
    title: 'Universe Game - Synergy and Heart\'s Desire Exercise',
    summary: 'An instructor\'s outline for the "Universe Game," a group exercise created by Choices International in 1988. The game teaches synergy and heart\'s desire through an experiential format where participants must balance going for how they feel versus giving up what they want. The outline covers a 45-minute opening that includes defining synergy (the whole is greater than the sum), examples of synergy in families, bodies, nature, and companies, and defining heart\'s desire as what you really want versus what you think you want. It details when the Universe (facilitator) issues fines (visible fighting, lack of synergy, desperation, losing heart\'s desire after getting it) and rewards (genuine giving, demonstrated synergy, asking for something).',
    authorship: 'Choices International, 1988. The footer on both content pages reads "Choices International, 1988."',
    filename: '4g.pdf',
    type: 'pdf',
    category: 'Transformation Programs',
  },

  // Radical Love & Radical Choices (17)
  // Ordered: RLF guidebooks, then RLF materials and presentations, Radical Love workbooks, Mindful Living, Radical Choices DLT programs, then reference and press
  {
    id: '12a',
    title: 'Natural Leadership: A Core Competency of Clarity',
    summary: 'A guidebook published by the Radical Love Foundation presenting Judith Orloff\'s "Natural Leadership" methodology, which frames clarity as the essential core competency for effective leadership. The document defines six guiding principles: Personal Responsibility, Sharing Direct Experience, Knowing Yourself, Honoring Our Word, Being Authentic, and Applying Skillful Means, each broken into specific sub-competencies with stated benefits. Developed over 30 years of organizational participation, it positions Natural Leadership as an innate ability to do the right thing when informed by clarity, authenticity, and natural ethics.',
    authorship: 'Judith Orloff, M.Ed. and the Radical Love Design Team. Published by Radical Love Foundation, Boulder, Colorado. Version dated June 16, 2013.',
    filename: '12a.pdf',
    type: 'pdf',
    category: 'Radical Love & Radical Choices',
  },
  {
    id: '12b',
    title: 'Awakened Relationships: A Core Competency of Unconditional Love',
    summary: 'A workbook published by the Radical Love Foundation (co-founded by Judith Orloff and Melissa Stuart) that defines and teaches the concept of "Awakened Relationships" through six guiding principles: Personal Response-Ability, Sharing Direct Experience, Being Authentic, Knowing Yourself, Honoring Our Word, and Applying Skillful Means. Each principle is presented with key tenets, benefits, and accompanying "Notes and Reflections" pages for the reader\'s personal journaling, along with a central diagram showing how the six competencies interconnect around themes of clarity, integrity, oneness, synergy, and natural wisdom.',
    authorship: 'Judith Orloff and the Radical Love Design Team, published by Radical Love Foundation, version September 7, 2013',
    filename: '12b.pdf',
    type: 'pdf',
    category: 'Radical Love & Radical Choices',
  },
  {
    id: '13d',
    title: 'Radical Love Foundation - Workshop Materials, Conference Proposals, Teaching Content, and Bios',
    summary: 'A compilation of Radical Love Foundation materials by Judith Orloff and co-founder Melissa Stuart, including workshop descriptions, conference proposals (notably for the Science and Nonduality Conference 2010 in San Rafael, California), core teaching content on topics like "Pure Inseeing," "Pure Listening," and "Pure Speaking," email correspondence with conference organizers, the Practicum Principles one-sheet, the Foundation\'s Purpose/Vision/Mission statement, detailed workshop outlines covering conditioning, unconditioned awareness, family systems, and archetypes, plus professional bios for both Judith and Melissa.',
    authorship: 'Written and compiled by Judith Orloff, M.Ed., with contributions from Melissa Stuart, M.A., and email correspondence from Alexa Cloud and Salina Storozuk. Created for internal use by the Radical Love Foundation team and for conference submissions.',
    filename: '13d.pdf',
    type: 'pdf',
    category: 'Radical Love & Radical Choices',
  },
  {
    id: '13e',
    title: 'Radical Love Foundation - The Future of Executive Leadership Development',
    summary: 'A slide presentation from the Radical Love Foundation (copyright 2013) on the future of executive leadership development. Critiques the present state of leadership education for ignoring the \'shadow of the leader,\' relying on projection and judgment, using linear competencies, and approaching change with fear. Identifies systemic problems including discomfort with responsibility without empowerment, inadequate feedback methodology, focus on output over outcome, and emotional intelligence not being easily learned or modeled. Envisions a future where authentic relationships and natural leadership competencies thrive, emotional literacy skills are as important as reading, community connection is valued, and clarity, experiential learning, Radical Listening, and Radical Speaking are mainstays.',
    authorship: 'Radical Love Foundation, copyright 2013. Developed from relationships with Bank of America, Fleet BankBoston, Midas, Johnson & Johnson, and other Fortune 500 executives.',
    filename: '13e.pdf',
    type: 'pdf',
    category: 'Radical Love & Radical Choices',
  },
  {
    id: '16b',
    title: 'Radical Love Foundation - Readings, Poems, and Workshop Teaching Materials',
    summary: 'A collection of teaching materials used in Radical Love Foundation workshops, copyright 2011. Includes the parable "Now" about a monk\'s urgency for presence, the poem "The Kama Sutra of Kindness: Position Number 3" by Mary Mackey, W.N. Murray\'s "Commitment" passage from The Scottish Himalayan Expedition, a section on emotions as waves of energy referencing Dr. Candace Pert\'s "Molecules of Emotion," teachings on the reactive self and conditioning, Prigogine\'s dissipative structures applied to learning, integrity patterns and pitfalls, negative bonding, a "Living the Future Now" Winter 2012 program description ($1500 tuition), a poem by Guthema Roba, and a Rumi poem translated by Nader Khalili.',
    authorship: 'Radical Love Foundation (RLF), copyright 2011. Teaching materials compiled by Judith Orloff and associates. Includes works by Mary Mackey, W.N. Murray, Candace Pert (referenced), Guthema Roba, Rumi (translated by Nader Khalili), and Karlfried Graf von Durkheim.',
    filename: '16b.pdf',
    type: 'pdf',
    category: 'Radical Love & Radical Choices',
  },
  {
    id: '16c',
    title: 'Radical Love Participant Workbook',
    summary: 'A participant workbook for the Radical Love program containing interactive exercises, journaling pages, and teaching content organized around core concepts. Includes "The Choice of Love" poem contrasting fear and love, exercises on introduction and deepest desires, the "Birth to Now" timeline exercise, teachings on the Reactive/Simulated Self and childhood conditioning (with extensive handwritten annotations), "Feelings not Experienced... Persist and Control You" diagrams, the "Mom and Dad Game" role-play exercise, "Approval and Disapproval Fantasy," "True Desire" mortality exercise, a memorial service eulogy-writing exercise, an excerpt from Karlfried Graf von Durkheim\'s "The Way of Transformation," and the "Commitment" passage by W.N. Murray.',
    authorship: 'Radical Love Foundation / Judith Orloff. Contains extensive handwritten annotations and edits throughout (particularly on the Reactive Self pages, suggesting revision from \'Reactive Self\' to \'Simulated Self\'). Includes excerpted works by Karlfried Graf von Durkheim and W.N. Murray.',
    filename: '16c.pdf',
    type: 'pdf',
    category: 'Radical Love & Radical Choices',
  },
  {
    id: '18',
    title: 'The Art & Science of Mindful Living - Participant Workbook',
    summary: 'A comprehensive multi-week participant workbook for \'The Art & Science of Mindful Living\' program by the Radical Love Foundation. Organized into at least 7 weekly sessions covering Context (choosing love vs. fear, the F.A.V.O.R. method for empathic communication, context vs. content in communication, recipes for setting context), Insight (emotions as energy waves, shadow work, childhood reflection, true desire exercises, the DeepSee app), Personal Responsibility toward self (projection, judgment, dishonesty exercises), Personal Responsibility toward others (making amends, radical listening adapted from Peter Fenner, right action), Authenticity (reactive vs. authentic sharing, role-play \'Jumping Paradigms\' exercise with homeless vet scenario in Boulder), and Integrity/Lying (cleaning up the mess of dishonesty). Each week includes self-assessment forms, interim assignments with the DeepSee app, journaling pages, and partner-sharing exercises. Includes poems by e.e. cummings and Bette Midler\'s \'The Rose,\' quotes from Werner Erhard and Michael C. Jensen, Rumi via Coleman Barks, and the W.N. Murray commitment passage.',
    authorship: 'Radical Love Foundation / Judith Orloff. The workbook incorporates teachings adapted from Peter Fenner, quotes from Werner Erhard, Michael C. Jensen (HBS professor), W.N. Murray, and poems by e.e. cummings and Bette Midler. References the DeepSee app as a companion tool.',
    filename: '18.pdf',
    type: 'pdf',
    category: 'Radical Love & Radical Choices',
  },
  {
    id: '21b',
    title: 'Conditioning\'s Last Stand - Integrity',
    summary: 'A brief two-page document consisting of a handwritten title page reading \'Conditioning\'s last stand - INTEGRITY\' in pink marker, followed by a page describing an alternative information-communicative theory of brain organization covering neural circuits, holographic information distribution, memory storage, and quantum mechanisms of consciousness.',
    authorship: 'Handwritten title page likely by Judith Orloff. Scientific text excerpted from an academic paper on brain organization.',
    filename: '21b.pdf',
    type: 'pdf',
    category: 'Radical Love & Radical Choices',
  },
  {
    id: '21c',
    title: 'Radical Choices Leadership Programs - Learning Methodology Overview',
    summary: 'A single-page overview of the Radical Choices learning methodology, explaining how the programs link emotion, spiritual relevance, and intellectual content to participant experience through a combination of logical, emotional, and spiritual experiences, abstract concepts, physical experiences, and taking action. Notes that programs can be customized to organizations.',
    authorship: 'Radical Choices. No individual author credited.',
    filename: '21c.pdf',
    type: 'pdf',
    category: 'Radical Love & Radical Choices',
  },
  {
    id: '9b',
    title: 'Radical Choices - Leadership in Recovery Day One Workbook',
    summary: 'Day One participant workbook for the Radical Choices "Leadership in Recovery" program using Disruptive Learning Technology (DLT). Covers the foundations of leadership vision and beliefs, how beliefs create perceived reality, the secret of powerful leadership through self-relationship, the Triune Brain model for whole brain learning, presenting content effectively, and the physical manifestation of communication difficulties. Includes the six DLT principles (Insight, Personal Responsibility, Authenticity, Integrity, Clear Mind, Awakened Action) and a group activity called Thumbs Up/Thumbs Down where teams create and present organizational strategies.',
    authorship: 'Ali Boaldin / Radical Choices LLC (contact: Office@radicalchoicesllc.com). Triune Brain figure credited to Energetics Institute, copyright 2010.',
    filename: '9b.pdf',
    type: 'pdf',
    category: 'Radical Love & Radical Choices',
  },
  {
    id: '15b',
    title: 'Radical Choices - Leadership in Recovery Day Two Workbook',
    summary: 'Day Two participant workbook for the Radical Choices "Leadership in Recovery" program using Disruptive Learning Technology (DLT), copyright 2015. Focuses on removing blocks to leadership through understanding the Reactive Self (automatic responses from the past), developing personal responsibility as \'response-ability,\' recognizing reactions as pitfalls (judgment, interpretation, projection), dissolving reactions, cultivating authenticity, maintaining integrity, and applying the six DLT principles. Includes recovery-specific scene study activities set in addiction treatment facilities and a \'Cleaning Up The Mess\' integrity self-assessment exercise.',
    authorship: 'Ali Boaldin / Radical Choices LLC, copyright 2015 (contact: Office@radicalchoicesllc.com).',
    filename: '15b.pdf',
    type: 'pdf',
    category: 'Radical Love & Radical Choices',
  },
  {
    id: '9e',
    title: 'Radical Choices and Emotional Literacy - Program Materials and Kosmos Essay',
    summary: 'A collection of related documents on Radical Choices methodology and Emotional Literacy in business contexts. Includes a 4-page overview of emotional intelligence (EQ) and emotional literacy, a Kosmos Essay Draft v2 on conditioning and the Six Principles of Being, materials on Real Impact Learning and Emotional Literacy, and an Orloff Consulting version applying emotional literacy in the workplace. Supersedes document 9c by including all three branding era versions plus additional material.',
    authorship: 'Multiple versions attributed to Radical Choices, Real Impact Learning Inc., and Orloff Consulting. Connected to Judith Orloff\'s work.',
    filename: '9e.pdf',
    type: 'pdf',
    category: 'Radical Love & Radical Choices',
  },
  {
    id: '15c',
    title: 'Radical Choices - Train the Trainer Certification Program, Session Three: "Beyond Suffering - The Naked Bald Truth"',
    summary: 'Session Three participant workbook for the Radical Choices Disruptive Learning Technology (DLT) Train the Trainer Certification Program, copyright 2016, subtitled \'Beyond Suffering: The Naked Bald Truth.\' This is a three-day intensive designed to prepare trainers to take DLT into the world through relationships, work, and interactions. Day One (\'Know What Is / Own What Is\') features a provocative mock trial activity where God/Great Spirit/Unconditioned is put on trial for crimes against humanity, explores nondual awareness vs. conditioned experience using Peter Fenner\'s framework, examines how mental \'pictures\' and personal Greek tragedy \'fatal flaws\' shape our lives, and introduces Being vs. Doing through e.e. cummings poetry. Day Two (\'Clarity\') includes live DLT demonstrations by Judith, Jungian archetypes in literature (Hero, Mother, Innocent Youth, Magician, Doppelganger, Scapegoat, Villain), and a \'Speakable Me\' activity for sharing reactive states without judgment. Day Three (\'Taking It Out In The World\') covers organizational DLT demos, Clear Mind practice, and Awakened Action presentations on escaping mass consciousness conditioning.',
    authorship: 'Judith Orloff / Ali Boaldin / Radical Choices LLC, copyright 2016. Marked \'CONFIDENTIAL - This workbook is the confidential intellectual property of Radical Choices, LLC - DO NOT DISSEMINATE.\' Nondual Awareness diagram credited to Peter Fenner.',
    filename: '15c.pdf',
    type: 'pdf',
    category: 'Radical Love & Radical Choices',
  },
  {
    id: '18a',
    title: 'The End of Your World - Adyashanti Interview Transcript (Sounds True)',
    summary: 'A 19-page transcript of an in-depth interview between Sounds True publisher Tami Simon and spiritual teacher Adyashanti, excerpted from his book \'The End of Your World.\' Topics covered include the nature of spiritual awakening as a change of perspective rather than a blissful state, the distinction between nonabiding and abiding awakening using the \'rocket ship\' metaphor, the mystery of what fuels awakening, \'Velcro thoughts\' and the narrowing gap between thought and seeing through it, pure feeling vs. thought-derived emotion, the gut as an intuitive sense organ, pure anger from an undivided state, the ego co-opting awakening into missionary zeal, the dangers of spiritual inflation, the inner voice as guide vs. superego, finding one\'s own way rather than relying on a teacher or tradition, his experience of \'final awakening\' at age 32 including seeing past lives, death as the next experience of consciousness, and his teaching that \'waking up is dying.\' Includes handwritten annotations throughout marking key passages.',
    authorship: 'Interview conducted by Tami Simon (Sounds True publisher) with Adyashanti. Excerpted from the book \'The End of Your World\' published by Sounds True. The document includes handwritten annotations (likely by Judith Orloff or a Radical Love Foundation reader) marking passages about secondary thought patterns, pure emotions vs. duplications of thinking, and pure anger.',
    filename: '18a.pdf',
    type: 'pdf',
    category: 'Radical Love & Radical Choices',
  },

  // Choices & Personal Development (10)
  // Ordered: Core programs (Choices Weekend, intake form, follow-up) first, then evening series and corporate retreat, then standalone exercises
  {
    id: '11c',
    title: 'The Choices Weekend - Instructor\'s Manual',
    summary: 'The complete instructor\'s manual for The Choices Weekend, a three-day personal development seminar created by Judith Orloff-Falk and Peg Doubleday and published by Educational Discoveries (QED). The manual provides a detailed hour-by-hour program outline across three days with specific teaching scripts, guided meditations, exercises, poster diagrams, and music cues. Day One covers belief systems, the Bliss/Now model of how sensations become feelings and beliefs, reactions as cover-ups, and the 7-11 Question Game. Day Two teaches the Seven Steps to Get Out of Reaction, personal responsibility, unconditional love, control as fear of loss, intimacy versus \'into-me-see,\' projection, and handling projections in five steps. Day Three covers vision quests, the Model for Change (an 8-step diagram from Conscious Choice through Resistance, Illusion/Chaos, Acknowledgment, Breakthrough, to Vision), and closes with action planning and a \'Recipe for Ecstatic Sex.\' Includes a music guide listing 28 songs with their emotional purposes.',
    authorship: 'Copyright 1992 by Educational Discoveries (QED). Revised 12/4/91 and 1/9/92 by \'ch.\' The creators of the course are identified within the text as Judith Orloff-Falk and Peg Doubleday. A handwritten annotation on page 16 reads \'Judy Care\' (likely Judith Orloff-Falk\'s married name or note).',
    filename: '11c.pdf',
    type: 'pdf',
    category: 'Choices & Personal Development',
  },
  {
    id: '15a',
    title: 'The Choices Weekend - Personal Discovery Form',
    summary: 'A multi-page intake questionnaire given to participants before The Choices Weekend seminar. The form collects extensive personal history including birth circumstances (planned, wanted, birth complications, twin, premature, breech, caesarean), family dynamics (parents\' relationship, divorce, siblings, deaths), childhood experiences (illnesses, injuries, emotional traumas), sexual and reproductive history (separate sections for women and men covering pregnancies, miscarriages, abortions), current health status (illnesses, injuries, medications, psychiatric care, allergies, surgeries), personal psychology (desires, fears, self-perception, thoughts about life and relationships), previous workshop experience, and emergency contact information. Participants are asked to bring the completed form to the Weekend.',
    authorship: 'No author or publisher credited on the form itself. Based on its title \'The Choices Weekend Personal Discovery Form,\' it was created by the same organization (QED / Educational Discoveries) that produced the Choices Weekend program, founded by Judith Orloff-Falk and Peg Doubleday.',
    filename: '15a.pdf',
    type: 'pdf',
    category: 'Choices & Personal Development',
  },
  {
    id: '11b',
    title: 'Graduate Training Outline - Choices Weekend Follow-up',
    summary: 'An instructor\'s guide for a 6-week follow-up program designed for graduates of the Choices Weekend seminar, published by QED (Quantum Educational Discoveries) in 1990. The program meets three hours weekly in a residential setting with 8-12 participants at $375 per person. It outlines six sessions covering Connection, Model for Change and Reaction, Projection, Responsibility and Integrity (Parts I and II), and a final Demonstration session, each with specific exercises such as partner role-play for projection, values identification on flip charts, and a personal change project that participants track throughout the six weeks.',
    authorship: 'Published by QED, Inc. (Quantum Educational Discoveries), P.O. Box 918, Williston, Vermont 05495. Copyright 1990. Dated 12/11/90. No individual author named.',
    filename: '11b.pdf',
    type: 'pdf',
    category: 'Choices & Personal Development',
  },
  {
    id: '10',
    title: 'QED Evening Series Manual: Instructor Outlines and Logistics Guidelines',
    summary: 'An operations manual for the QED (Quantum Educational Discoveries) Evening Series workshop program, copyrighted 1990 and revised in 1991. Contains two complete instructor outlines for evening seminars: "How Many People Are Really in Your Bed?" (about relationships, intimacy, parental patterns, chemistry, secrets, and a "recipe for ecstatic sex") and "Ending the Fight" (a five-step process for resolving conflict). Also includes Evening Workshop Logistics Guidelines with detailed job descriptions, room setup diagrams, supply checklists, and music playlists.',
    authorship: 'Created by Quantum Educational Discoveries (QED), copyrighted 1990, with instructor outlines revised 6/11/91 and 6/25/91, and logistics guidelines revised 7/1/91. Written as internal training and operations materials for QED instructors and logistics teams.',
    filename: '10.pdf',
    type: 'pdf',
    category: 'Choices & Personal Development',
  },
  {
    id: '9',
    title: 'Choices for Success - Participant Workbook (Company Retreat, May 1995)',
    summary: 'Participant workbook for the Choices for Success company retreat held May 18-19, 1995, produced by Educational Discoveries. Guides participants through exercises on paradigm shifts, head vs. heart framework, childhood purpose, beliefs, feelings, reactions, personal responsibility, unconditional love, projection, control, and intimacy. Includes reflective journal prompts, illustrated concept pages, and notes pages.',
    authorship: 'Created by Judith Orloff and Educational Discoveries (5495 Arapahoe Road, Suite 205, Boulder, CO 80303). Written for corporate retreat participants.',
    filename: '9.pdf',
    type: 'pdf',
    category: 'Choices & Personal Development',
  },
  {
    id: '10b',
    title: 'Personal Responsibility, Emotional Mastery and Success - A New Beginning',
    summary: 'A conceptual essay published by Real Impact Learning, Inc. (2004) that argues for embracing the full range of human emotions rather than repressing them. It introduces the concepts of "Backup Behaviors" (defensive reactions like blaming, denying, justifying) versus "Flexible Behaviors" (honest emotional expression leading to wisdom), and defines "Emotional Mastery" and "emotional literacy" as skills for reading and expressing emotions without projection. The document draws on brain research about emotional processing systems and references the importance of personal responsibility as the ability to respond in the present moment with unlimited options.',
    authorship: 'Real Impact Learning, Inc. Copyright 2004. No individual author credited.',
    filename: '10b.pdf',
    type: 'pdf',
    category: 'Choices & Personal Development',
  },
  {
    id: '4c',
    title: 'Sources of Information - Head, Heart, and Soul (Chapter 10)',
    summary: 'Chapter 10 from a larger book exploring six sources of information available for decision-making: three internal (head, heart, and soul) and three external (support from others, mass consciousness, and universal consciousness). The chapter explains how the "head" operates from past programming and belief systems, the "heart" provides present-moment emotional information, and the "soul" reveals core values and life purpose. It includes interactive exercises comparing head vs. heart responses, discusses true guilt vs. false guilt, the role of support in personal change, and introduces universal consciousness as a source of intuition and knowing. Personal anecdotes from Peg and Judith illustrate the concepts, including stories about marriage, relationships, and trusting intuition.',
    authorship: 'Co-authored by Judith Orloff and Peg (last name not stated in this chapter). This is Chapter 10 from a book they wrote together, with both contributing personal anecdotes. A handwritten note at the top reads "Hand out Thurs. night - read before go to bed."',
    filename: '4c.pdf',
    type: 'pdf',
    category: 'Choices & Personal Development',
  },
  {
    id: '4d',
    title: 'The 7-11 Game - Ethics and Choices Role Play Exercise',
    summary: 'A role-play exercise designed for use in the Choices or Learning Choices program. Participants play teenagers (about age 14) who have witnessed a respected classmate (the class president) rob a 7-11 store and knock down an elderly lady. They adopt assigned personality roles (Thief, Liberal, Moral, Peacemaker, Fair) and role-play a group conversation confronting the classmate. The exercise includes an optional guided meditation that projects participants forward in time at 10, 20, 40, and 50 year intervals to examine the long-term consequences of their choices on relationships, career, self-respect, and feelings about death. Concludes with sharing and the option to play the song "In a Simple Way."',
    authorship: 'No specific author credited. Created as part of the Choices / Learning Choices curriculum, associated with Judith Orloff\'s programs.',
    filename: '4d.pdf',
    type: 'pdf',
    category: 'Choices & Personal Development',
  },
  {
    id: '4e',
    title: 'Learning Choices - Crossing the Abyss Game',
    summary: 'A team-building exercise from the Learning Choices program where participants simulate climbing Mount Learning to 10,000 feet. Teams of participants must cross a taped "abyss" on the floor using only three mats as stepping surfaces, with no talking allowed during the climb. The exercise is designed to demonstrate integrity, personal responsibility, teamwork, congruence, and how people respond to moment-to-moment conditions in a group setting. Includes detailed setup instructions (5ft by 20ft taped squares), five rules for the game, and a structured debrief with discussion questions about commitment, teamwork, assumed roles, success, and helping other teams.',
    authorship: 'No specific author credited. Created as part of the Learning Choices curriculum, headed "Learning Choices" at the top of each page.',
    filename: '4e.pdf',
    type: 'pdf',
    category: 'Choices & Personal Development',
  },
  {
    id: '4f',
    title: 'Mom and Dad Game - Parental Identity Exercise',
    summary: 'A 30-minute role-play exercise where participants embody their parents to explore inherited beliefs and patterns. In step one, participants become their same-sex parent at age 20, speaking about love, sex, marriage, children, money, work, power, intimacy, and success. In step two, they become that parent at their current age discussing the same topics. In step three, they switch to become their opposite-sex parent. The worksheet includes reflection prompts asking "How are you like your Mother?" and "How are you like your Father?" A handwritten note in red asks "Is this for everyone? Or just kids?" suggesting it was used across different program audiences.',
    authorship: 'No specific author credited. Associated with Judith Orloff\'s Choices program curriculum. Contains a handwritten editorial note in red ink.',
    filename: '4f.pdf',
    type: 'pdf',
    category: 'Choices & Personal Development',
  },

  // Friendship Circle (7)
  // Ordered: Foundational philosophy, correspondence, proposals and contracts, then related programs
  {
    id: '3f',
    title: 'Letter from the Rebbe on the Care and Education of Jewish Children with Disabilities',
    summary: 'A letter from the Lubavitcher Rebbe dated 22 Av, 5739 (1979), responding to a request for his views on the care and education of Jewish children with intellectual disabilities. The Rebbe provides detailed guidelines including: treating each case individually rather than applying group rules, starting from the premise that disabilities are temporary and improvable, avoiding exaggerated expectations while giving guarded encouragement, involving trainees in leadership roles, addressing the controversy around \'group homes\' with a recommendation for individual evaluation, emphasizing the importance of Jewish education and identity for children with disabilities (not treating it as a secondary concern), and the therapeutic value of religious observance and community belonging. The letter closes with reference to the Lubavitch principle of \'Ve\'ohavta Lereacha Kamocha\' (Love your fellow as yourself) and a blessing to the recipient in their capacity as Regional Chairman of the Council For Mental Retardation.',
    authorship: 'The Lubavitcher Rebbe (Menachem Mendel Schneerson, implied by title \'The Rebbe Writes\' and Lubavitch reference)',
    filename: '3f.pdf',
    type: 'pdf',
    category: 'Friendship Circle',
  },
  {
    id: '3e',
    title: 'Friendship Circle Email Correspondence - Shemtov, Grossbaum, and Orloff',
    summary: 'A collection of email correspondence (November 2003 through May 2004) between Rabbi Yehuda Shemtov, Rabbi Zalman Grossbaum, and Judith Orloff regarding the Friendship Circle PowerPoint presentation and recruitment program. Includes Shemtov\'s initial outreach (November 30, 2003) asking Judith to create a powerful enrollment process for teenagers volunteering with special needs children, Grossbaum\'s offer to join via conference call, Judith\'s discovery questions about the FC program and target audience, detailed responses from both rabbis about the program structure and presentation needs (15-45 minute format, multi-sensory for teens), conference call notes from May 18, 2004 discussing the broader vision of sensitivity training and anti-bullying (with mentions of Norm and Emma as content collaborators), and early brainstorming notes for the recruitment presentation including sample video scripts and opening/closing talking points.',
    authorship: 'Rabbi Yehuda Shemtov (yshemtov@earthlink.net), Rabbi Zalman Grossbaum (Zalman@NJJewish.com), Judith Orloff (jorloff@o-dconsulting.com), and Sarah Cardet (referenced in conference call notes)',
    filename: '3e.pdf',
    type: 'pdf',
    category: 'Friendship Circle',
  },
  {
    id: '3b',
    title: 'Friendship Circle Recruitment Presentation - Draft Enrollment Concept',
    summary: 'A draft enrollment concept document for the Lubavitch Friendship Circle\'s teen volunteer recruitment presentation, created by Orloff Consulting in 2004. The document explains the situation (captive audiences of 50-75 teens, many reluctant), outlines a 25-30 minute experiential presentation format led by rabbis including: opening context-setting, video/slideshow of teens and disabled children, activities exploring what participants love and can\'t stand, debriefs connecting shared hopes and fears, and wrap-up on commitment. Includes extended time options such as \'Gloves of Arthritis\' (disability simulation), trust walks, and \'Being Disabled\' imagination exercises. Contains assumptions, time estimates (147 hours total), and investment estimates ($5,000 for design/development, $500-$1,000 per center).',
    authorship: 'Orloff Consulting 2004 (Judith Orloff). Handwritten notes on cover reference \'25 minute pres. with 3 add ons\' and \'people to interview at their end, 5 of each: teenager & kids.\'',
    filename: '3b.pdf',
    type: 'pdf',
    category: 'Friendship Circle',
  },
  {
    id: '3c',
    title: 'Friendship Circle Disabilities Sensitivity Training and Anti-Bullying Workshop Proposal',
    summary: 'A proposal document for the Friendship Circle\'s Disabilities Sensitivity Training and Anti-Bullying Workshop, targeting middle and high school students. Includes history of the Friendship Circle (founded 1994 in Detroit, Michigan), its growth to 42 cities with 3,000+ families and 5,500+ teen volunteers, and the proposed workshop format using discussions, improvisational exercises, and videos. The plan of action describes enlisting Orloff Consulting of Boulder, Colorado to create the workshop, with a pilot through Friendship Circles in California, Michigan, New Jersey, and Pennsylvania (30 workshops in first four months), anticipating reaching 15,000 teenagers in the first year. Contact information for Rabbi Zalman Grossbaum, Executive Director of Friendship Circle in Livingston, NJ.',
    authorship: 'Friendship Circle (Rabbi Zalman Grossbaum, Executive Director, Livingston, NJ). Orloff Consulting of Boulder, Colorado enlisted to create the workshop.',
    filename: '3c.pdf',
    type: 'pdf',
    category: 'Friendship Circle',
  },
  {
    id: '3d',
    title: 'Friendship Circle Sensitivity Training - Consulting Contract and Program Design',
    summary: 'A comprehensive consulting contract and program design document from Orloff Consulting (2004) for the Friendship Circle sensitivity training project. Contains a cover page, the presentation concept (situation overview referencing the Rebbe\'s quote about treating disabilities as temporary), a detailed 25-30 minute program outline (opening, video, slideshow, activity, debrief, wrap-up), additional activity options (Being Disabled exercise, Gloves of Arthritis, Hitchhiker role-play), facilitator training requirements (tolerance for conflict, creating safe environments), deliverables (recruitment program, presentation materials, train-the-trainer program), assumptions about research interviews, and a financial investment section ($5,000 for design/development with payment in quarters, $500-$1,000 per center for first 10, then $750-$1,500). Includes a phased timeline from Research through Train-the-Trainer.',
    authorship: 'Orloff Consulting 2004 (Judith Orloff)',
    filename: '3d.pdf',
    type: 'pdf',
    category: 'Friendship Circle',
  },
  {
    id: '16a',
    title: 'The Inward Bound Institute Proposal - "Touching Reality" Series (Fragment)',
    summary: 'A single-page fragment from a proposal by Orloff Learning, Inc. for \'The Inward Bound Institute\' and its \'Touching Reality\' series. The document describes Rabbi Yehuda Shemtov of the Glazer Center in Yardley, PA, and his innovative educational programming that combines ancient Kabbalistic sources with modern learning applications such as self-discovery, accelerative learning, and emotional intelligence. The proposal describes Shemtov\'s mission to share the teachings of Chassidic tradition and Kabbalah through a new learning methodology, seeking financial partners for world-wide programs. Dated 2006.',
    authorship: 'Orloff Learning, Inc. (Judith Orloff\'s company). Written in support of Rabbi Yehuda Shemtov\'s programs.',
    filename: '16a.pdf',
    type: 'pdf',
    category: 'Friendship Circle',
  },
  {
    id: '1',
    title: 'The Power of the Sacred Living Letters: The Kabbalah Book of Change',
    summary: 'A spiritual guidebook co-authored by Judith Orloff and Jasmyne Boswell that presents each of the 22 Hebrew letters of the Alef-Bet as tools for personal transformation and self-discovery rooted in Kabbalistic teachings. Each letter chapter includes its meaning, numerical value, calendar connection, reflective questions, shadow aspects, and suggested "right actions." The book draws on Chassidic stories, Torah commentary, and teachings from figures like the Baal Shem Tov and various Rabbis to connect ancient Jewish mysticism with practical spiritual growth exercises.',
    authorship: 'Judith Orloff, M.Ed. and Jasmyne Boswell. The Authors Notes section (pages 81-83) includes personal reflections from both authors. Orloff describes herself as a spiritual guide, non-dual transpersonal therapist and author who co-designed programs with Lubavitch of Bucks County. Boswell describes her inspiration from Celtic Runes leading to a Kabbalistic exploration of the Hebrew Alphabet.',
    filename: '1.pdf',
    type: 'pdf',
    category: 'Friendship Circle',
  },

  // Corporate Leadership Training & Educational Discoveries (14)
  // Ordered: Flagship MBL and leadership programs, then client-specific programs, learning design, Model for Change suite, Accounting Game suite, press and case studies
  {
    id: '7',
    title: 'Mastery of Business Leadership (MBL) - Complete Program Curriculum',
    summary: 'The complete curriculum and session materials for the Mastery of Business Leadership (MBL) program, a corporate leadership training program developed by Judith Orloff through Orloff Consulting, Inc. (Boulder, CO) and delivered under Choices International. The document compiles the full program overview, detailed session notes and transcripts for all eight to nine multi-day sessions (spanning July 1989 through April 1990), assignment sheets, scheduling documents, supplementary articles, a program evaluation form, and participant worksheets. Topics covered across sessions include organizational vision and beliefs, intention and motivation, listening and communication, stress management and conflict resolution, integrity, empowerment and synergy, responsibility and delegation, and demonstrating leadership through self-mastery.',
    authorship: 'Created by Judith Orloff through Orloff Consulting, Inc., and delivered under the Choices International brand. Sessions were facilitated by Judith, Peg, and Joseph at The Broker Inn in Boulder, CO. Designed for business leaders and entrepreneurs seeking to integrate emotional literacy, authenticity, and personal development into their corporate leadership practice.',
    filename: '7.pdf',
    type: 'pdf',
    category: 'Corporate Leadership Training & Educational Discoveries',
  },
  {
    id: '27a',
    title: 'The Art and Science of Leadership - Participant Workbook',
    summary: 'A comprehensive multi-day corporate leadership training workbook published by Educational Discoveries, Inc. in 1997. Covers emotional literacy (Authentic Self vs. Reactive Self), authentic leadership tools (Space, Enrollment, Common Ground, Gradient, Ritual), the F.A.V.O.R. method for handling audience questions, and the science of transformation based on Ilya Prigogine\'s dissipative structures theory. The appendix includes extended readings on workplace family dynamics (Dr. Harry Levinson), lateral thinking, effective listening, and a recommended reading list including Judith Orloff\'s "Choices for Success."',
    authorship: 'Created by Educational Discoveries, Inc. (copyright 1997). Appendix incorporates articles by Sally Van Wagenen Keil, Paul C. Blodgett, and Richard M. Harris. Recommended reading includes Judith Orloff\'s \'Choices for Success\' (with Peg Doubleday).',
    filename: '27a.pdf',
    type: 'pdf',
    category: 'Corporate Leadership Training & Educational Discoveries',
  },
  {
    id: '6c',
    title: 'Discovery and Change (Personal Responsibility Training) - Complete Curriculum and Instructor\'s Manual',
    summary: 'Complete curriculum package for "Discovery and Change," an eight-session personal responsibility training program developed under the ETP (Educational Training Program) framework. The document includes both participant handout materials (readings, worksheets, exercises) dated 04-07-1992 and a detailed instructor\'s manual (revised 04-23-1991) covering session-by-session teaching notes, facilitation guidance, and day-by-day schedules for each multi-day weekend session. Topics span emotional autobiography, responsibility, family dynamics, core values, vision and purpose, projection, body integration, sexuality, personal integrity, and commitment to change. The program also references "Disruptive Learning Technology" as its pedagogical framework and incorporates curated readings from authors including Vaclav Havel, Ian Frazier, and R. Buckminster Fuller.',
    authorship: 'Created as part of the ETP (Educational Training Program) organization. The instructor\'s manual is labeled \'ETP Instructor\'s Manual\' and revised 04-23-1991. The participant materials are dated 04-07-1992. Judith Orloff\'s specific role is not named in the sampled pages, but the document is part of her archive and reflects the personal growth training work she was involved with.',
    filename: '6c.pdf',
    type: 'pdf',
    category: 'Corporate Leadership Training & Educational Discoveries',
  },
  {
    id: '20a',
    title: 'WHY\'s Guide to the Human Side of CPR - Complete Training Program',
    summary: 'A comprehensive four-day corporate training seminar workbook created for Cargill, designed to teach the human and emotional side of CPR (Corporate Process Reengineering/Change). The program includes multiple interactive modules: "The Chronicles of WHY" (a narrative role-playing exercise set aboard the S.S. Destiny), "WHY: A Game of Integrity" (a commodity trading simulation with play money and role cards), "The Synergy Game" (a non-verbal communication exercise), and concluding sections on consultant tools, action planning, and stress relief. Includes custom watercolor cover art, printable game materials (play money branded "The World of WHY" with "In Each Other We Trust"), and structured reflection worksheets.',
    authorship: 'Created by Judith Orloff as part of her corporate consulting practice. Designed for Cargill employees undergoing a major CPR (change/reengineering) initiative. References the Seven C\'s Consulting Model and the FAVOR Method as proprietary frameworks.',
    filename: '20a.pdf',
    type: 'pdf',
    category: 'Corporate Leadership Training & Educational Discoveries',
  },
  {
    id: '19',
    title: 'Applying Accelerated Learning to Course Design - Training Workbook',
    summary: 'A comprehensive training workbook produced by Educational Discoveries that teaches instructional designers how to apply accelerated learning principles to course design. Presents the proprietary "Whole Being Model for Teaching and Learning" integrating mind, body, heart, and spirit. Includes a complete copy of The Accounting Game (copyright 1983), the Choices International Model for Change (copyright 1990), a learning styles inventory based on the 4MAT system, and reference materials on brain research, dissipative structures, and Deming\'s quality principles applied to education.',
    authorship: 'Created by Educational Discoveries (co-founded by Judith Orloff). Compiles proprietary frameworks alongside licensed third-party materials: The Accounting Game (1983), Choices Paradigm for Change (1990), 4MAT System by Bernice McCarthy, brain research from Tony Buzan, and a 1990 article by Lewis A. Rhodes on Deming. Mind maps credited to Rob Evans.',
    filename: '19.pdf',
    type: 'pdf',
    category: 'Corporate Leadership Training & Educational Discoveries',
  },
  {
    id: '24',
    title: 'Core Technology Programs - Train-The-Trainer (TTT) Workbook',
    summary: 'A Train-The-Trainer workbook created by Educational Discoveries, Inc. (dated 05.28.98) designed to teach instructors how to present accelerative learning seminars. The workbook covers neuroscience foundations including the Triune Brain Model (reptilian complex, limbic system, neocortex), right brain/left brain research by Professor Robert Ornstein and Dr. Paul MacLean, and instructor methodology concepts such as Setting the Context, the Instructor\'s Safety Net (Space, Enrollment, Common Ground, Gradient, Ritual, Discovery), Reaction and the "Stop, Look, Listen, Act" tool, the F.A.V.O.R. method for handling questions, and Giving and Receiving Support.',
    authorship: 'Created by Educational Discoveries, Inc., the corporate training company founded by Judith Orloff (President/CEO). Written for instructors being certified to deliver Educational Discoveries\' accelerative learning programs.',
    filename: '24.pdf',
    type: 'pdf',
    category: 'Corporate Leadership Training & Educational Discoveries',
  },
  {
    id: '25',
    title: 'The Nature of Conflict - Course Materials and Conflict Resolution Participant Workbook',
    summary: 'A comprehensive conflict resolution training package from Educational Discoveries, Inc. (part of the Provant Solution), combining a detailed course outline for an 8-hour program and a participant workbook. The course outline covers sources of conflict, personal responsibility, the Conflict Resolution Model, individual and team conflict resolution activities, and action planning. The participant workbook includes Tom Crum\'s "Magic of Conflict" philosophy, a step-by-step conflict resolution framework, and "The Model for Change" with its 10-step paradigm shift process and role-playing "Players" exercise.',
    authorship: 'Created by Educational Discoveries, Inc. (part of the Provant Solution), with Judith Orloff as President/CEO. Quotes Tom Crum\'s "Magic of Conflict." Written for individuals at all levels within large organizations.',
    filename: '25.pdf',
    type: 'pdf',
    category: 'Corporate Leadership Training & Educational Discoveries',
  },
  {
    id: '25a',
    title: 'The Model for Change - Supplementary Materials',
    summary: 'A collection of materials related to Educational Discoveries\' proprietary "Model for Change" framework. It includes the cover page for "The Model for Change: Steps for Creating a Paradigm Shift in People," an excerpt from Chapter 11 of "Choices for Success: Your Happiness In Your Own Hands" laying out an 11-step process for navigating change, an "About Educational Discoveries" overview page, a colorful visual map of the change model cycle, and an introductory text describing the 10-step process.',
    authorship: 'Created by Educational Discoveries (EDI), based in Boulder, CO. Judith Orloff was president and CEO. The chapter excerpt comes from the book "Choices for Success: Your Happiness In Your Own Hands."',
    filename: '25a.pdf',
    type: 'pdf',
    category: 'Corporate Leadership Training & Educational Discoveries',
  },
  {
    id: '25b',
    title: 'The Model for Change For Managers - Program Overview',
    summary: 'A program overview document for "The Model for Change For Managers," a two-day training program created by Educational Discoveries (copyright 2001, dated 10.12.01). The document outlines nine training modules across two days covering topics including paradigm shifts, the 8-step Model for Change, resistance vs. reaction, giving and receiving support, creating an environment for change, communication tools (the 6 Tools for Communicating and F.A.V.O.R.), the Synergy Game, and taking ownership for change. It also includes color-coded role-play scenario cards for improvisation activities featuring characters like Sulky Supervisor, Fresh as a Newborn Babe, Willing Worker, Wary Worker, and Marginal Manager.',
    authorship: 'Created by Educational Discoveries (noted as \'Part of the Provant Solution\'). Judith Orloff was a co-founder of Educational Discoveries. Written for facilitators delivering the Model for Change program to managers of teams undergoing organizational change.',
    filename: '25b.pdf',
    type: 'pdf',
    category: 'Corporate Leadership Training & Educational Discoveries',
  },
  {
    id: '25c',
    title: 'Breakthrough - Model for Change Participant Workbook',
    summary: 'A participant workbook for the \'Breakthrough\' corporate leadership training program developed by Educational Discoveries (part of the Provant Solution). The workbook teaches the \'Model for Change,\' a 10-step framework for navigating organizational and personal paradigm shifts, covering concepts like Response-Ability, Purpose, Mission, Vision, Objectives, Paradox, Reaction, Illusion, Crisis, Chaos of Creation, Perturbation, Congruence, and Synergy. It draws on thought leaders including Amir Levy and Uri Merry, Edward Simon, John D. Adams, Marilyn Ferguson, and Stephen Covey.',
    authorship: 'Created by Educational Discoveries (Part of the Provant Solution), co-founded by Judith Orloff. Copyright 2001, dated 10.12.01. Designed as a participant workbook for corporate leadership training programs.',
    filename: '25c.pdf',
    type: 'pdf',
    category: 'Corporate Leadership Training & Educational Discoveries',
  },
  {
    id: '22',
    title: 'The Accounting Game - Instructor Manual',
    summary: 'A comprehensive instructor manual for teaching "The Accounting Game," a full-day interactive seminar created by Educational Discoveries that teaches fundamental accounting concepts through a lemonade stand simulation. The manual provides word-for-word scripts and detailed stage directions across an Introduction, Level 1, and Level 2, guiding instructors through teaching balance sheets, income statements, assets, liabilities, owner\'s equity, accrual accounting, accounts receivable, accounts payable, retained earnings, and prepaid expenses using colored game pieces, props, and role-playing. The pedagogical approach emphasizes Accelerative Learning with whole-brain engagement, participation, permission to make mistakes, and multisensory engagement including music, breathing exercises, and physical movement.',
    authorship: 'Created by Educational Discoveries (copyright holder). Internal training document for certified instructors delivering The Accounting Game seminar. This copy has the name \'Darrell\' handwritten on the cover, likely Darrell Mullis (co-author of the Accounting Game book). Judith Orloff was co-founder of Educational Discoveries.',
    filename: '22.pdf',
    type: 'pdf',
    category: 'Corporate Leadership Training & Educational Discoveries',
  },
  {
    id: '23',
    title: 'The Accounting Game: Complete Instructor Manual (Levels I-VI)',
    summary: 'A comprehensive instructor manual for The Accounting Game, an experiential learning program developed by Educational Discoveries that teaches accounting and financial literacy through a lemonade stand simulation. The manual guides instructors through six progressive levels using a two-column "What You Do / What You Say" format, covering balance sheets, income statements, accrual vs. cash accounting, accounts receivable, retained earnings, depreciation, inventory management, and cash flow statements. The teaching methodology incorporates physical props, group exercises, affirmation cards, and a diploma ceremony.',
    authorship: 'Created by Judith Orloff and Educational Discoveries as a proprietary instructor training manual. Designed for certified instructors delivering The Accounting Game to corporate and adult education audiences.',
    filename: '23.pdf',
    type: 'pdf',
    category: 'Corporate Leadership Training & Educational Discoveries',
  },
  {
    id: '19a',
    title: 'The Accounting Game - Book Publishing Documents',
    summary: 'A collection of materials related to the publication of "The Accounting Game" book by Educational Discoveries (EDI) and Sourcebooks. It includes a draft foreword explaining the accelerative learning methodology behind the book, a press release announcing the joint venture between EDI and Source Books with co-authors Darrell Mullis and CEO Judith Orloff, and email correspondence from March 1998 between Larry Bograd and Todd Stocke at Sourcebooks regarding author credit order.',
    authorship: 'Compiled materials involving Judith Orloff (CEO of EDI), Larry Bograd (EDI\'s legal/business representative), Todd Stocke (Managing Editor at Sourcebooks), and Darrell Mullis (EDI\'s top presenter and co-author).',
    filename: '19a.pdf',
    type: 'pdf',
    category: 'Corporate Leadership Training & Educational Discoveries',
  },
  {
    id: '26',
    title: 'Educational Discoveries - Conference, Press & Case Study Materials',
    summary: 'A compilation of press coverage, conference materials, and corporate case studies related to Educational Discoveries (EDI). It includes pages from the 2nd Annual Emotional Intelligence Summit program featuring speakers like Peter Salovey, Richard Boyatzis, David Whyte, and Judith Orloff. It also contains a Training Magazine article about EDI\'s work with Midas International on their culture change initiative, and detailed case studies of EDI\'s corporate training projects for Midas, Bank of America, Cablevision, and FleetBoston Financial.',
    authorship: 'Compiled by Educational Discoveries (EDI), part of the Provant Solution. Judith Orloff is identified as president and CEO. The Training Magazine article is reprinted from the June 2001 issue. The EI Summit materials are from Linkage Inc.',
    filename: '26.pdf',
    type: 'pdf',
    category: 'Corporate Leadership Training & Educational Discoveries',
  },

  // Academic & Scholarly Work (6)
  // Ordered: Dissertation first (capstone work), then application, research papers
  {
    id: '28',
    title: 'Using Nonduality to Ameliorate Early Childhood Trauma: An Autoethnography (Doctoral Dissertation, 2020)',
    summary: 'Judith Orloff\'s doctoral dissertation submitted to Fielding Graduate University for the degree of Doctor of Education, copyright 2020. The study explores how early childhood trauma can define a person\'s future and proposes nonduality, a Buddhist non-conceptual model of healing suffering, as a foundational therapeutic model that could be used universally with all modalities of therapy. Using autoethnography, the dissertation tells Judith\'s personal story of childhood abuse, postpartum depression and psychosis leading to misdiagnosis and psychiatric hospitalization, and her journey to resilience through nonduality. Chapter Four is an extended personal narrative covering her life from Philadelphia childhood through founding Burlington College, discovering Peter Fenner\'s nonduality framework, and developing her six-step "Nonduality in Action" model presented in Chapter Five.',
    authorship: 'Judith Orloff, EdD. Submitted to Fielding Graduate University. Committee: Szabi Istai-Zee, PhD (Chair), Anna M. DiStefano, EdD, Ira P. Glovinsky, PhD, Donna Farren, Alan Davis, PhD.',
    filename: '28.pdf',
    type: 'pdf',
    category: 'Academic & Scholarly Work',
  },
  {
    id: '20',
    title: 'Fielding Graduate University EdD Application',
    summary: 'Judith Orloff\'s application materials for the EdD program at Fielding Graduate University, including a Statement of Purpose and a Self-Reflective Essay dated June 2, 2016. The Statement of Purpose describes her pursuit of Disruptive Learning Technology (DLT), a patent-pending process with an app called DeepSee in the Apple Store, designed to help children transcend childhood conditioning. The Reflective Essay traces her professional journey from meeting Dr. Steward LaCasce at the University of Pennsylvania in 1971, co-founding the Vermont Institute of Community Involvement (VICI, later Burlington College), creating the Noogenesis program at Shelburne Farms, working as a psychotherapist, and developing her methodology over 40+ years. It also includes a professional resume listing roles at Horizon House, University of Pennsylvania, Burlington College, Carriage House Associates in Health, Choices International, Educational Discoveries, and Orloff Learning/Real Impact Learning.',
    authorship: 'Judith Orloff (applicant ID 3964194). Written for Fielding Graduate University EdD application. The reflective essay references Dr. Steward LaCasce, Carol Moore (President of Burlington College), and various collaborators throughout her career.',
    filename: '20.pdf',
    type: 'pdf',
    category: 'Academic & Scholarly Work',
  },
  {
    id: '2a',
    title: 'Dissertation Critique - Nowhere Man by Tracy John Skipp',
    summary: 'Judith Orloff\'s academic critique of Tracy John Skipp\'s 2010 doctoral dissertation "Nowhere Man: Autoethnographic Reflections on Identity, Family, and Leadership" for the ELC 727 Methods Action Research course with Dr. Anna DiStefano at Fielding Graduate University. Orloff evaluates Skipp\'s use of autoethnography to explore leadership intimacy, his identification with Saint Francis of Assisi, his struggle with Franciscan Roman Catholic values in a university administration setting, and his three-part framework of leadership as intimacy with self, others, and developmental intimacy. The critique addresses the study\'s framing concepts (personalism, intimacy, fatherhood), research methods (360 assessment, interviews, reflective journaling), and data collection challenges.',
    authorship: 'Judith Orloff. Written for ELC 727 Methods Action Research course, submitted 3/11/17. Instructor: Dr. Anna DiStefano, Fielding Graduate University. The dissertation being critiqued is by Tracy John Skipp (Educational Leadership, 2010).',
    filename: '2a.pdf',
    type: 'pdf',
    category: 'Academic & Scholarly Work',
  },
  {
    id: '2b',
    title: 'Insight as a Core Mechanism of Mindfulness: An Action Research Project',
    summary: 'An action research project by Judith Orloff at Fielding Graduate University investigating whether insight is a core mechanism of mindfulness practice. The paper distinguishes between Western (conceptual, Jon Kabat-Zinn) and Eastern (Buddhist, non-conceptual) mindfulness approaches, focusing on the latter. It proposes a study with 20 participants using narrative inquiry methodology, including in-depth interviews, a 28-day daily email survey with four-question assessments, and focus group exit interviews. The research questions examine whether being insightful leads to deeper mindfulness, whether insight leads to beneficial behavior, and whether insight reduces blame through reduced projection. Includes a 63-question autobiography questionnaire, mobile app mockups from Orloff\'s organization Radical Choices, Inc., and references to her six principles of mindfulness.',
    authorship: 'Judith Orloff, Fielding Graduate University. References her organization Radical Choices, Inc. and the app DeepSee. Mentions collaboration with Doubleday (Orloff & Doubleday 2015). The paper engages with work by Jon Kabat-Zinn, Ellen Langer, Chade meng Tan, Valerie Bentz, Peter Fenner, and Bessel van der Kolk.',
    filename: '2b.pdf',
    type: 'pdf',
    category: 'Academic & Scholarly Work',
  },
  {
    id: '3a',
    title: 'Dissolving Adverse Childhood Conditioning through a Mindfulness Curriculum for Parents and Children from Preschool through High School',
    summary: 'A brief assignment by Judith Orloff for Lee Mahon\'s ELC-721 course at Fielding Graduate University (submitted February 15, 2017) outlining her vision for a mindfulness/self-awareness curriculum addressing drugs, violence, and detachment in young people. She describes 45 years of exploring methodologies to dissolve negative childhood conditioning, references the concept of \'trance state\' from Four Arrows, and discusses her plan to use Phenomenology as her dissertation methodology. The document also mentions her intent to explore Theories of Change with Montessori early childhood education for Nicola\'s class. References include Thomas Verny\'s \'The Secret Life of the Unborn Child\' and Frederick Leboyer\'s \'Birth without Violence.\'',
    authorship: 'Judith Orloff. Written as Assignment 3 for ELC-721-17SPI course, submitted to Lee Mahon on February 15, 2017, at Fielding Graduate University.',
    filename: '3a.pdf',
    type: 'pdf',
    category: 'Academic & Scholarly Work',
  },
  {
    id: '3g',
    title: 'Assessment of Montessori Teacher Training Using Theories of Change',
    summary: 'An academic paper by Judith Orloff for the ELC-726 Theories of Change course at Fielding Graduate University examining how Theory of Change (TOC) frameworks can be applied to assess Montessori teacher training programs. The paper explores the Montessori emphasis on teacher self-awareness, non-judgmental observation, and self-assessment, and argues these align well with TOC methodology. It includes an interview with Ann Velasco, Director of Training at the Southwest Institute for Montessori Studies, a five-step TOC framework for teacher assessment, and references to Fritjof Capra\'s concept of paradigm. Appendices include a cartoon, Orloff\'s original 21-element Model for Change (developed in 2001 as CEO of Educational Discoveries), an illustrated Model for Change diagram, and a Championing Change Activity Feedback Form.',
    authorship: 'Judith Orloff, M.Ed. Written for ELC-726: Theories of Change course at Fielding Graduate University. References her prior work as CEO of Educational Discoveries, a leadership and development company. Includes interview data from Ann Velasco, Director of Training at Southwest Institute for Montessori Studies.',
    filename: '3g.pdf',
    type: 'pdf',
    category: 'Academic & Scholarly Work',
  },

  // Business & Intellectual Property (4)
  // Ordered: Patent, trademark, book outline, marketing materials
  {
    id: '6a',
    title: 'Patent Application: Experiential Learning System and Process for Developing Functional Self-Awareness',
    summary: 'A provisional patent application (ORLOFF.JUDITH-LZ.001PP) for an experiential learning system and process that combines psychometrics and practical mindfulness through six sequential behavioral stages to develop functional self-awareness and produce predictable, sustainable behavior changes. The six stages are Insight, Personal Responsibility, Authenticity, Integrity, Clear Mind, and Awakened Action. The system uses a whole-brain approach targeting the neocortex, limbic system, and amygdala to dissolve past conditioning and reprogram neural pathways, with implementations including mobile apps, online courses, physical courses, and certification programs.',
    authorship: 'Judith Orloff is listed as the inventor/applicant. The document reference number is ORLOFF.JUDITH-LZ.001PP, indicating it was prepared by or for her legal representation.',
    filename: '6a.pdf',
    type: 'pdf',
    category: 'Business & Intellectual Property',
  },
  {
    id: '6b',
    title: 'USPTO Trademark Office Action: "Life Solutions Through Disruptive Learning Technology"',
    summary: 'A USPTO Office Action (Serial No. 86829570) issued on 4/7/2016 to Radical Choices, LLC regarding their trademark application for "Disruptive Learning Technology," filed 11/23/2015 by Ali Boaldin. The examining attorney (John M. Gartner, Law Office 102) refused registration on the grounds that the mark is merely descriptive of the applicant\'s communication and experiential learning services, and also raised issues with the identification and classification of services, multiple class requirements, and specimen refusal. The document includes the original TEAS RF application, the trademark search summary, dictionary definition exhibits for "disruptive," "technology," and "learn," and the submitted specimen showing the "Life Solutions Through Disruptive Learning Technology" marketing material for Radical Choices.',
    authorship: 'Office Action authored by John M. Gartner, Trademark Examining Attorney, Law Office 102, USPTO. Application filed by Ali Boaldin as Manager of Radical Choices, LLC, Boulder, Colorado.',
    filename: '6b.pdf',
    type: 'pdf',
    category: 'Business & Intellectual Property',
  },
  {
    id: '14',
    title: 'Book Outline - Radical Love: Awakened Relationships and Natural Leadership',
    summary: 'A detailed book outline dated 12/18/2013 for \'Radical Love: Awakened Relationships and Natural Leadership\' by Judith Orloff and Melissa (co-founders of the Radical Love Foundation). The book is structured in five parts across ten chapters, built around six guiding principles: Personal Responsibility, Knowing Our Self, Being Authentic, Honoring Our Word, Sharing Direct Experience, and Applying Skillful Means. Each chapter includes stories, exercises, and meditations designed to help readers develop awakened relationships and natural leadership through dissolving conditioned responses and living with clarity and authenticity.',
    authorship: 'Co-authored by Judith Orloff and Melissa (last name not specified). The file path references \'C:\\Users\\Alexa\\Documents\\00 NewRadical Books\\Book Outline18Dec13v2.docx\', suggesting Alexa may have been involved in document preparation. The outline notes their seven-year collaboration and study leading to the Radical Love Foundation.',
    filename: '14.pdf',
    type: 'pdf',
    category: 'Business & Intellectual Property',
  },
  {
    id: '27b',
    title: 'Educational Discoveries - Program Descriptions & Marketing Materials',
    summary: 'A collection of program descriptions and marketing materials from Educational Discoveries, Inc. (Boulder, Colorado), dated 1999. The document showcases the company\'s corporate training programs built around Emotional Literacy and accelerative learning methodologies, including standard programs (Model for Change, Mastery of Business Leadership, Art and Science of Management) and custom-designed programs for major clients such as Bank of America/NationsBank, WellBridge (Monsanto), Cargill, Ernst & Young, Mobil EHS, Caterpillar Purchasing, Wilcox Hospital, and Union Central Life Insurance. Also includes marketing flyers for The Designing Game (a course design workshop), The Art and Science of Leadership, The Financial Game for Decision Making, custom training services, and an organizational transformation workshop series.',
    authorship: 'Published by Educational Discoveries, Inc., Boulder, Colorado. Copyright 1999, Educational Discoveries, Inc. Some materials carry the UnionCentral branding, indicating co-branded client deliverables.',
    filename: '27b.pdf',
    type: 'pdf',
    category: 'Business & Intellectual Property',
  },
]
export function getDocumentById(id: string): SoftaDocument | undefined {
  return documents.find((doc) => doc.id === id)
}

// Category order: personal voice first, then core work ranked by depth and
// importance, then progressively more institutional/dry material at the bottom.
const categories: { name: string; description: string; color: string }[] = [
  {
    name: 'Writings, Speeches & Correspondence',
    description: 'In between the programs and the training materials, there are a handful of moments where you get a sense of Judith herself. That\'s what this section is: a newspaper profile in the Boulder Daily Camera, hand-drawn notes from a presentation on presence and secrets, letters with W. Edwards Deming (someone she deeply admired), an interview where she talks through her thinking on emotional intelligence, and a convocation speech at Burlington College, the school she co-founded.',
    color: '#E6908A',
  },
  {
    name: 'Transformation Programs',
    description: 'This is where the deep work lives. Judith\'s Extended Teaching Program took participants through months of intensive sessions on self-awareness, family dynamics, relationships, and personal integrity. This section collects the instructor manuals, workbooks, and session guides from that curriculum. Much of her later work grew directly out of what\'s here.',
    color: '#C8BE6E',
  },
  {
    name: 'Radical Love & Radical Choices',
    description: 'Judith spent decades refining her approach to personal transformation. Through the Radical Love Foundation and Radical Choices LLC, she distilled that work into six guiding principles and applied them to leadership, relationships, mindful living, and recovery work. This section collects the guidebooks, workbooks, and training programs from that later chapter of her career.',
    color: '#D48D78',
  },
  {
    name: 'Choices & Personal Development',
    description: 'The Choices Weekend and its companion programs were designed to give people practical tools in a concentrated setting. This section collects those shorter-format programs: weekend seminars, evening sessions, corporate retreats, and standalone exercises focused on recognizing patterns and making more conscious choices.',
    color: '#EDBBCC',
  },
  {
    name: 'Friendship Circle',
    description: 'Judith brought her experiential learning approach to the Friendship Circle, a Lubavitch program that pairs teen volunteers with children who have special needs. This section covers that work: the correspondence that started the project, consulting proposals, workshop designs, sensitivity training programs built around compassion through direct experience, and her co-authored Kabbalah guidebook exploring the Hebrew Alef-Bet as tools for transformation.',
    color: '#C8BE6E',
  },
  {
    name: 'Corporate Leadership Training & Educational Discoveries',
    description: 'Through Educational Discoveries and Orloff Consulting, Judith brought emotional awareness into the corporate world as a core leadership skill. This section covers programs she designed for organizations like Bank of America, Cargill, Midas International, and Mobil, along with The Accounting Game, conflict resolution workshops, and the Model for Change framework.',
    color: '#6DA0C4',
  },
  {
    name: 'Academic & Scholarly Work',
    description: 'Later in her career, Judith pursued doctoral work at Fielding Graduate University, researching the connection between mindfulness and insight. This section includes her doctoral dissertation on using nonduality to ameliorate childhood trauma, her academic papers, and her research on Montessori education and theories of change.',
    color: '#E6908A',
  },
  {
    name: 'Business & Intellectual Property',
    description: 'The business side of protecting and promoting the work. This section has the patent filings, trademark applications, a book outline, and marketing materials that formalized the methodology Judith developed across her career.',
    color: '#EDBBCC',
  },
]

export function getCategories(): { name: string; description: string; color: string }[] {
  return categories.filter((cat) =>
    documents.some((doc) => doc.category === cat.name)
  )
}

export function getDocumentsByCategory(category: string): SoftaDocument[] {
  return documents.filter((doc) => doc.category === category)
}

export function getThumbnailPath(doc: SoftaDocument): string {
  if (doc.type === 'image') {
    return `/documents/${doc.filename}`
  }
  const name = doc.filename.replace(/\.pdf$/i, '')
  return `/thumbnails/${name}.png`
}
